from enum import Enum

class DeploymentGuardrailResult(Enum):
    APPROVED = "APPROVED"
    REQUIRES_TRANSFORMATION = "REQUIRES_TRANSFORMATION"
    BLOCKED_PRINCIPLE_VIOLATION = "BLOCKED_PRINCIPLE_VIOLATION"
    BLOCKED_CULTURAL_SENSITIVITY = "BLOCKED_CULTURAL_SENSITIVITY"
    ERROR = "ERROR"
