#!/usr/bin/env python3
"""
Semantic Mirror Environment Flag Manager

Safely flips Semantic Mirror feature flags via local .env file.
Provides idempotent flag management for production cutover operations.

Usage Examples:
    python scripts/semantic_mirror_flip.py --enable --no-shadow
    python scripts/semantic_mirror_flip.py --disable --shadow
    python scripts/semantic_mirror_flip.py --print
"""

import argparse
import os
import sys


ENV_FILE = ".env.semantic_mirror"


def read_env_file():
    """Read current environment settings from .env file."""
    env_vars = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and '=' in line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    return env_vars


def write_env_file(env_vars):
    """Write environment settings to .env file."""
    with open(ENV_FILE, 'w', encoding='utf-8') as f:
        f.write("# Semantic Mirror Environment Configuration\n")
        f.write("# Generated by semantic_mirror_flip.py\n\n")
        for key, value in sorted(env_vars.items()):
            f.write(f"{key}={value}\n")


def determine_mode(enabled, shadow):
    """Determine semantic mirror operational mode."""
    if enabled and not shadow:
        return "enabled"
    elif not enabled and shadow:
        return "shadow"
    elif not enabled and not shadow:
        return "disabled"
    else:  # enabled and shadow
        return "shadow"  # Shadow takes precedence for safety


def flip_flags(enable=None, shadow=None):
    """Flip semantic mirror flags and return new state."""
    # Read current settings
    env_vars = read_env_file()

    # Get current values (default to safe disabled state)
    current_enabled = env_vars.get("NOVA_SEMANTIC_MIRROR_ENABLED", "0").strip() == "1"
    current_shadow = env_vars.get("NOVA_SEMANTIC_MIRROR_SHADOW", "1").strip() == "1"

    # Apply changes if specified
    if enable is not None:
        current_enabled = enable
    if shadow is not None:
        current_shadow = shadow

    # Update environment variables
    env_vars["NOVA_SEMANTIC_MIRROR_ENABLED"] = "1" if current_enabled else "0"
    env_vars["NOVA_SEMANTIC_MIRROR_SHADOW"] = "1" if current_shadow else "0"

    # Write updated configuration
    write_env_file(env_vars)

    # Determine and return mode
    mode = determine_mode(current_enabled, current_shadow)
    return mode, current_enabled, current_shadow


def print_current_state():
    """Print current semantic mirror configuration."""
    env_vars = read_env_file()
    enabled = env_vars.get("NOVA_SEMANTIC_MIRROR_ENABLED", "0").strip() == "1"
    shadow = env_vars.get("NOVA_SEMANTIC_MIRROR_SHADOW", "1").strip() == "1"
    mode = determine_mode(enabled, shadow)

    print(f"Current Configuration ({ENV_FILE}):")
    print(f"  NOVA_SEMANTIC_MIRROR_ENABLED={env_vars.get('NOVA_SEMANTIC_MIRROR_ENABLED', '0')}")
    print(f"  NOVA_SEMANTIC_MIRROR_SHADOW={env_vars.get('NOVA_SEMANTIC_MIRROR_SHADOW', '1')}")
    print(f"  MODE={mode}")


def main():
    """Main flag management application."""
    parser = argparse.ArgumentParser(
        description="Semantic Mirror Flag Manager",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/semantic_mirror_flip.py --enable --no-shadow   # Go live
  python scripts/semantic_mirror_flip.py --disable --shadow     # Shadow mode
  python scripts/semantic_mirror_flip.py --print               # Show current
        """
    )

    group = parser.add_mutually_exclusive_group()
    group.add_argument('--enable', action='store_true',
                      help='Enable Semantic Mirror feature')
    group.add_argument('--disable', action='store_true',
                      help='Disable Semantic Mirror feature')

    shadow_group = parser.add_mutually_exclusive_group()
    shadow_group.add_argument('--shadow', action='store_true',
                             help='Enable shadow mode (metrics only)')
    shadow_group.add_argument('--no-shadow', action='store_true',
                             help='Disable shadow mode (full operation)')

    parser.add_argument('--print', action='store_true',
                       help='Print current configuration without changes')

    args = parser.parse_args()

    try:
        # Handle print-only mode
        if args.print:
            print_current_state()
            return

        # Determine flag changes
        enable_flag = None
        shadow_flag = None

        if args.enable:
            enable_flag = True
        elif args.disable:
            enable_flag = False

        if args.shadow:
            shadow_flag = True
        elif args.no_shadow:
            shadow_flag = False

        # Apply changes
        if enable_flag is not None or shadow_flag is not None:
            mode, enabled, shadow = flip_flags(enable_flag, shadow_flag)
            print(f"MODE={mode}")
            print(f"NOVA_SEMANTIC_MIRROR_ENABLED={enabled}")
            print(f"NOVA_SEMANTIC_MIRROR_SHADOW={shadow}")
            print(f"Configuration written to {ENV_FILE}")
        else:
            # No changes requested, show current state
            print_current_state()

    except Exception as e:
        print(f"Error managing semantic mirror flags: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
